<a href="https://colab.research.google.com/github/leekikiyun/python_programming/blob/main/Week%2011/Week%2011%20Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 11 Assignment - NumPy

NumPy 공식 문서의 예제를 처음부터 "Reshaping and flattening multidimensional arrays" 절까지 따라 입력하고 실행한 결과입니다.

출처: https://numpy.org/doc/stable/user/absolute_beginners.html

## How to import NumPy

In [1]:
import numpy as np

## Reading the example code

In [2]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

In [3]:
a.shape

(2, 3)

## Why use NumPy?

## What is an “array”?

## Array fundamentals

In [4]:
a = np.array([1, 2, 3, 4, 5, 6])

In [5]:
a

array([1, 2, 3, 4, 5, 6])

In [6]:
a[0]

np.int64(1)

In [7]:
a[0] = 10

In [8]:
a

array([10,  2,  3,  4,  5,  6])

In [9]:
a[:3]

array([10,  2,  3])

In [10]:
b = a[3:]

In [11]:
b

array([4, 5, 6])

In [12]:
b[0] = 40

In [13]:
a

array([10,  2,  3, 40,  5,  6])

In [14]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [15]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
a[1, 3]

np.int64(8)

## Array attributes

In [17]:
a.ndim

2

In [18]:
a.shape

(3, 4)

In [19]:
len(a.shape) == a.ndim

True

In [20]:
a.size

12

In [21]:
import math

In [22]:
a.size == math.prod(a.shape)

True

In [23]:
a.dtype

dtype('int64')

## How to create a basic array

In [24]:
np.zeros(2)

array([0., 0.])

In [25]:
np.ones(2)

array([1., 1.])

In [26]:
np.empty(2) 

array([1., 1.])

In [27]:
np.arange(4)

array([0, 1, 2, 3])

In [28]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [29]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [30]:
x = np.ones(2, dtype=np.int64)

In [31]:
x

array([1, 1])

## Adding, removing, and sorting elements

In [32]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [33]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [34]:
a = np.array([1, 2, 3, 4])

In [35]:
b = np.array([5, 6, 7, 8])

In [36]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
x = np.array([[1, 2], [3, 4]])

In [38]:
y = np.array([[5, 6]])

In [39]:
np.concatenate((x, y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

## How do you know the shape and size of an array?

In [40]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [41]:
array_example.ndim

3

In [42]:
array_example.size

24

In [43]:
array_example.shape

(3, 2, 4)

## Can you reshape an array?

In [44]:
a = np.arange(6)

In [45]:
print(a)

[0 1 2 3 4 5]


In [46]:
b = a.reshape(3, 2)

In [47]:
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [48]:
np.reshape(a, shape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

## How to convert a 1D array into a 2D array (how to add a new axis to an array)

In [49]:
a = np.array([1, 2, 3, 4, 5, 6])

In [50]:
a.shape

(6,)

In [51]:
a2 = a[np.newaxis, :]

In [52]:
a2.shape

(1, 6)

In [53]:
row_vector = a[np.newaxis, :]

In [54]:
row_vector.shape

(1, 6)

In [55]:
col_vector = a[:, np.newaxis]

In [56]:
col_vector.shape

(6, 1)

In [57]:
a = np.array([1, 2, 3, 4, 5, 6])

In [58]:
a.shape

(6,)

In [59]:
b = np.expand_dims(a, axis=1)

In [60]:
b.shape

(6, 1)

In [61]:
c = np.expand_dims(a, axis=0)

In [62]:
c.shape

(1, 6)

## Indexing and slicing

In [63]:
data = np.array([1, 2, 3])

In [64]:
data[1]

np.int64(2)

In [65]:
data[0:2]

array([1, 2])

In [66]:
data[1:]

array([2, 3])

In [67]:
data[-2:]

array([2, 3])

In [68]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [69]:
print(a[a < 5])

[1 2 3 4]


In [70]:
five_up = (a >= 5)

In [71]:
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [72]:
divisible_by_2 = a[a%2==0]

In [73]:
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [74]:
c = a[(a > 2) & (a < 11)]

In [75]:
print(c)

[ 3  4  5  6  7  8  9 10]


In [76]:
five_up = (a > 5) | (a == 5)

In [77]:
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


In [78]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [79]:
b = np.nonzero(a < 5)

In [80]:
print(b)

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In [81]:
list_of_coordinates= list(zip(b[0], b[1]))

In [82]:
for coord in list_of_coordinates:
    print(coord)

(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))


In [83]:
print(a[b])

[1 2 3 4]


In [84]:
not_there = np.nonzero(a == 42)

In [85]:
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


## How to create an array from existing data

In [86]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [87]:
arr1 = a[3:8]

In [88]:
arr1

array([4, 5, 6, 7, 8])

In [89]:
a1 = np.array([[1, 1],
               [2, 2]])

In [90]:
a2 = np.array([[3, 3],
               [4, 4]])

In [91]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [92]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [93]:
x = np.arange(1, 25).reshape(2, 12)

In [94]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [95]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]

In [96]:
np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]

In [97]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [98]:
b1 = a[0, :]

In [99]:
b1

array([1, 2, 3, 4])

In [100]:
b1[0] = 99

In [101]:
b1

array([99,  2,  3,  4])

In [102]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
b2 = a.copy()

## Basic array operations

In [104]:
data = np.array([1, 2])

In [105]:
ones = np.ones(2, dtype=int)

In [106]:
data + ones

array([2, 3])

In [107]:
data - ones

array([0, 1])

In [108]:
data * data

array([1, 4])

In [109]:
data / data

array([1., 1.])

In [110]:
a = np.array([1, 2, 3, 4])

In [111]:
a.sum()

np.int64(10)

In [112]:
b = np.array([[1, 1], [2, 2]])

In [113]:
b.sum(axis=0)

array([3, 3])

In [114]:
b.sum(axis=1)

array([2, 4])

## Broadcasting

In [115]:
data = np.array([1.0, 2.0])

In [116]:
data * 1.6

array([1.6, 3.2])

## More useful array operations

In [117]:
data = np.array([1, 2, 3])

In [118]:
data.max()

np.int64(3)

In [119]:
data.min()

np.int64(1)

In [120]:
data.sum()

np.int64(6)

In [121]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [122]:
a.sum()

np.float64(4.8595784)

In [123]:
a.min()

np.float64(0.05093587)

In [124]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

## Creating matrices

In [125]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [126]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [127]:
data[0, 1]

np.int64(2)

In [128]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [129]:
data[0:2, 0]

array([1, 3])

In [130]:
data.max()

np.int64(6)

In [131]:
data.min()

np.int64(1)

In [132]:
data.sum()

np.int64(21)

In [133]:
data = np.array([[1, 2], [5, 3], [4, 6]])

In [134]:
data

array([[1, 2],
       [5, 3],
       [4, 6]])

In [135]:
data.max(axis=0)

array([5, 6])

In [136]:
data.max(axis=1)

array([2, 5, 6])

In [137]:
data = np.array([[1, 2], [3, 4]])

In [138]:
ones = np.array([[1, 1], [1, 1]])

In [139]:
data + ones

array([[2, 3],
       [4, 5]])

In [140]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [141]:
ones_row = np.array([[1, 1]])

In [142]:
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

In [143]:
np.ones((4, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [144]:
np.ones(3)

array([1., 1., 1.])

In [145]:
np.zeros(3)

array([0., 0., 0.])

In [146]:
rng = np.random.default_rng()  # the simplest way to generate random numbers

In [147]:
rng.random(3) 

array([0.55759672, 0.95878741, 0.27038645])

In [148]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [149]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [150]:
rng.random((3, 2)) 

array([[0.03609221, 0.54821199],
       [0.19860357, 0.40454174],
       [0.50203404, 0.45938129]])

## Generating random numbers

In [151]:
rng.integers(5, size=(2, 4)) 

array([[4, 1, 4, 3],
       [2, 0, 2, 0]])

## How to get unique items and counts

In [152]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [153]:
unique_values = np.unique(a)

In [154]:
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [155]:
unique_values, indices_list = np.unique(a, return_index=True)

In [156]:
print(indices_list)

[ 0  2  3  4  5  6  7 12 13 14]


In [157]:
unique_values, occurrence_count = np.unique(a, return_counts=True)

In [158]:
print(occurrence_count)

[3 2 2 2 1 1 1 1 1 1]


In [159]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [160]:
unique_values = np.unique(a_2d)

In [161]:
print(unique_values)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [162]:
unique_rows = np.unique(a_2d, axis=0)

In [163]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [164]:
unique_rows, indices, occurrence_count = np.unique(
     a_2d, axis=0, return_counts=True, return_index=True)

In [165]:
print(unique_rows)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [166]:
print(indices)

[0 1 2]


In [167]:
print(occurrence_count)

[2 1 1]


## Transposing and reshaping a matrix

In [168]:
data.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [169]:
data.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [170]:
arr = np.arange(6).reshape((2, 3))

In [171]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [172]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [173]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

## How to reverse an array

In [174]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [175]:
reversed_arr = np.flip(arr)

In [176]:
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]


In [177]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [178]:
reversed_arr = np.flip(arr_2d)

In [179]:
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [180]:
reversed_arr_rows = np.flip(arr_2d, axis=0)

In [181]:
print(reversed_arr_rows)

[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [182]:
reversed_arr_columns = np.flip(arr_2d, axis=1)

In [183]:
print(reversed_arr_columns)

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [184]:
arr_2d[1] = np.flip(arr_2d[1])

In [185]:
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]


In [186]:
arr_2d[:,1] = np.flip(arr_2d[:,1])

In [187]:
print(arr_2d)

[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


## Reshaping and flattening multidimensional arrays

In [188]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [189]:
x.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [190]:
a1 = x.flatten()

In [191]:
a1[0] = 99

In [192]:
print(x)  # Original array

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [193]:
print(a1)  # New array

[99  2  3  4  5  6  7  8  9 10 11 12]


In [194]:
a2 = x.ravel()

In [195]:
a2[0] = 98

In [196]:
print(x)  # Original array

[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [197]:
print(a2)  # New array

[98  2  3  4  5  6  7  8  9 10 11 12]
